language: scala
scala:
    - "2.11.4"
jdk:
    - oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

