= Forklift

'''
The Enterprise Service Bus that supports building and deploying microservices quickly 
and easily. Forklift makes your life easier by providing common functionality that can
be shared by easily by annotating your code. To see what it can do for you check out the
full documentation.

link:doc/forklift.adoc[Documentation]


== Releases
* 0.17
** Add a separate thread to push replay logs to elastic search. This will allow msgs to be unhindered by the REST calls to ES. 
** Cleanup old errors from previous indexes before indexing the new doc. This can be inefficient, but guarantees the msg id is only in the system once.

* 0.16
** Fix bug that causes the max retries exceeded prop to not show in replay logs. 
** Fix bug that caused the retry startup search to fail due to having too many results.

* 0.15
** Elasticsearch implementation of retries and replay logs.

* 0.13
** Fix MultiThreaded consumer auto closing of resources.

* 0.12
** Auto closing of producers that are injected. 

* 0.11
** Close jms sessions correctly to avoid open session buildup on the amq nodes.

* 0.10
** Added a new @Property annotation that injects message properties into the consumer
** Extended @Config and @Headers to allow you to inject specific headers and config fields
** The @On decorator now is repeatable; one method can now intercept multiple lifecycle events
** Override classloader to delegate to the JVM libraries in cases where libs that start with these packages ("java", "com.sun", "sun", "org.xml", "org.w3c").

* 0.9
** Removed Scala build dependencies.
** Added the ability to close the forklift producer to avoid memory leaks in client code. 
** Added key/value pair send viathe forklift producer.
** Added a new On decorator that allows the lifecycle to be intercepted at any point by a method intercept.

* 0.8
** Remove spring completely from the core and replace with a service mechanism.

* 0.7
** Fix issue that would cause a consumer to stop processing due to a redelivery loop. This was caused any time a bad json parse occurred.

* 0.6
** Replay logger flush periodically if no messages are received. Helps guarantee nothing gets lost in the buffer.
** Log file configuration. Setup the container to drop a log file in /logs.
** Fix lost msgs that end up in the dead letter queue by using the core thread to process messages during a thread pool overload.
** Allow multiple Queue/Topic annotations per consumer. This helps when needing to monitor two different queues for fast vs slow processing.

* 0.5
** Spring setup fixes
** Main thread death fix when a consumer's spring context startup fails

* 0.4
** Allow the consul host to be specified
** Fix failover url construction when using service discovery with only one broker.

* 0.3
** Updates to docker container builds
** New arguments to allow retry/replay dirs to be set
** Allow two deployment directories to be scanned

* 0.2 
** Fix for property file injection into consumer.

* 0.1 
** Initial beta release
